#!/usr/bin/env bash
# Screen record or screen shot

readonly pb="https://ptpb.pw/?u=1"

picture() {
  maim -d 1 --format png /dev/stdout | curl -sF c=@- "$pb" | sed "s/$/.png/" | xcmenu -ic
}

video() {
  tmp=$(mktemp --suffix=.mkv)
  ffmpeg -y -video_size "$(wattr w "$(lsw -r)")x$(wattr h "$(lsw -r)")" -framerate 25 -f x11grab -i "$DISPLAY"  "$tmp"
  wait
  curl -sF c=@"$tmp" "$pb" | xcmenu -ic
}

## Main


case "$1" in
  snap)
    picture ;;
  vid)
    video ;; 
  stop)
    pkill -SIGINT ffmpeg ;;
esac
