#! /bin/sh
#
#   ██                                                           
#  ░██              ██████                                       
#  ░██       ██████░██░░░██ ███     ██ ██████████  ██████  █████ 
#  ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██░░██░░█ ██░░░██
#  ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██ ░██ ░ ░██  ░░ 
#  ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██ ░██   ░██   ██
#  ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██░███   ░░█████ 
#  ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░ ░░░     ░░░░░  
#

# workspaces 
bspc monitor -d I II III IV V VI VII VIII IX X

# autostart some programs
sxhkd &
nitrogen --restore &
yabar &
compton &


# looks
bspc config border_width         4
bspc config window_gap          32
bspc config focused_border_color '#5f8787'
bspc config normal_border-color '#111313'
bspc config presel_feedback_color '#111212'
bspc config urgent_border_color '#900900'


# behavior
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config top_padding 20


# rules
bspc rule -a qutebrowser desktop='^1' follow=on
bspc rule -a google-chrome-unstable desktop='^1' follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a termite -e rtorrent desktop='^8' state=floating
bspc rule -a mpv desktop='^4' state=pseudotiled
bspc rule -a vim desktop='^2'
bspc rule -a opera-developer desktop='^2' state=monocle

