#! /bin/sh

sxhkd &
nitrogen --restore &
compton &
$HOME/.config/polybar/launch.sh
#yabar &
dunst &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d browser term files mpd photo code reddit torrent chat 10

bspc config border_width         4
bspc config window_gap          4

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Set the border colors.
bspc config normal_border_color "$color2"
bspc config active_border_color "$color4"
bspc config focused_border_color "$color1"
bspc config presel_border_color "$color0"
bspc config presel_feedback_color "#111313"

#bspc config focused_border_color '#3BC7BC'
#bspc config normal_border-color '#515E71'
#bspc config presel_feedback_color '#3A6469'
#bspc config urgent_border_color '#900900'

bspc config top_padding 23

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a opera desktop='^1'
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a transmission-gtk desktop='^8' follow=on
