#!/bin/bash

## Init
# x and width don't matter yet
x=$(xdotool getmouselocation | cut -d ' ' -f 1 | cut -d ':' -f 2  )
y=28
width=75
height=24
font="-*-fixed-medium-*-*-*-13-*-*-*-*-*-*-*"
bgcolor='#333333'
fgcolor='#efefef'
# extract colors from color file
colorfile="$HOME/.config/herbstluftwm/colors.txt"
eins=$(sed '1q;d' "$colorfile")
zwei=$(sed '2q;d' "$colorfile")
drei=$(sed '3q;d'  "$colorfile")
vier=$(sed '4q;d'  "$colorfile")
fuenf=$(sed '5q;d'  "$colorfile")
sechs=$(sed '6q;d'  "$colorfile")
sieben=$(sed '7q;d'  "$colorfile")
acht=$(sed '8q;d'  "$colorfile")

battery() {
	attr=${1:-capacity}
	cat "/sys/class/power_supply/BAT0/$attr"
}

## Get Info
stat="$(battery status)"
cap="$(battery capacity)"
color="#efefef"

# charge state
if [ "$stat" = "Charging" ]
then
	stat="up"
elif [ "$stat" = "Discharging" ]
then
	stat="down"
else
	stat="full" # maybe
fi

# color of text
if [[ $cap -ge 80 ]]
then
	color="#00ff00"
elif [[ $cap -ge 70 ]]
then
	color="#4cb200"
elif [[ $cap -ge 60 ]]
then
	color="#669900"
elif [[ $cap -ge 50 ]]
then
	color="#777700"
elif [[ $cap -ge 40 ]]
then
	color="#996600"
elif [[ $cap -ge 20 ]]
then
	color="#b24c00"
elif [[ $cap -ge 1 ]]
then
	color="#ff0000"
else
	# shit is about to get fucked
	color="#0000ff"
fi

## Output Widget
output="^fg($color)$cap^fg()% $stat"
width=$(( $(dzen2-textwidth "$font" "$cap% $stat") + 16 ))
x=$(( $x - $width / 2 ))

echo "$output" \
	| dzen2 -p 3 -u \
		-e "button2=exit:0" \
		-x "$x" -y "$y" \
		-w "$width" -h "$height" \
		-fn "$font" \
-bg "$bgcolor" -fg "$fgcolor"
